<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Verify the user can register new account with multiple browsers.</description>
   <name>VoQuocKhanh_TMA _Solutions_InterView_Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e65b1f94-2057-443c-986f-143f4baec8dc</testSuiteGuid>
   <testCaseLink>
      <guid>199ba402-bfd2-47aa-917d-6abb94fbf724</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_the_user_can_register_new_account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eeffffed-78c2-448d-a194-abdb98cf2649</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dacb1783-656e-4e68-9936-8d4a1ef44ca1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_the_user_can_login_successfully</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e2d252e5-febf-47e5-8d9b-1131b61e4aed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_the_user_can_add_new_Customer_successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbf29cb-d8ea-40ae-977a-b784eaaa09e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d03a9ec-55b6-46d4-a51b-af9abbf22e64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd6218ce-e13d-4546-b355-c2387648d8c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b61cc1a1-0f42-41e6-9341-4b6a3b3bcc19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96c570c6-0b0e-4909-a310-bf6cf3452ca2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fa62dad-8726-4422-81f4-f1f070377e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae3eb6b2-c890-45c3-8f46-e2f0fb65a0b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58fe2580-8e58-463c-a805-4dc7bc47c436</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d109f91-181e-4ffc-bc4b-8940dffde408</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>262d4a53-0169-49ba-817e-7d0c3def2fd6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
